version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 10
  labels:
  - "dependencies"
  - "python"
  commit-message:
    prefix: "pip"
    include: "scope"

- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 5
  labels:
  - "dependencies"
  - "docker"
  commit-message:
    prefix: "docker"
    include: "scope"
